# Generated by Django 4.2.7 on 2023-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_like_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
