# Generated by Django 4.2.7 on 2023-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0003_alter_archive_archive_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='matiere',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='archive',
            name='niveau',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='archive',
            name='pays',
            field=models.CharField(max_length=255),
        ),
    ]
