# Generated by Django 4.2.7 on 2023-12-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0004_alter_archive_matiere_alter_archive_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
