# Generated by Django 4.2.7 on 2023-12-05 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='')),
                ('description', models.CharField(default='', max_length=255)),
                ('categorie', models.CharField(choices=[('vip', 'Prive'), ('public', 'public'), ('gratuit', 'gratuit'), ('payant', 'payant')], max_length=255)),
                ('organisateur', models.CharField(default='', max_length=255)),
                ('type_event', models.CharField(choices=[('scolaire', 'scolaire'), ('masterclass', 'masterclass')], max_length=255)),
                ('format_event', models.CharField(default='', max_length=255)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_heure_debut', models.DateTimeField(blank=True, null=True)),
                ('date_heure_fin', models.DateTimeField(blank=True, null=True)),
                ('billet', models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], max_length=50)),
                ('fuseau_horaire', timezone_field.fields.TimeZoneField(default='UTC')),
                ('intervenant', models.CharField(max_length=255)),
                ('event_likes', models.ManyToManyField(blank='True', default='None', related_name='event_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(default='', max_length=100)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
    ]
