# Generated by Django 4.2.7 on 2023-12-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
