# Generated by Django 4.2.7 on 2023-11-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('publicateur', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('financement', models.CharField(choices=[('partial', 'Partielle'), ('full', 'Complete')], default='', max_length=50)),
                ('nature', models.CharField(choices=[('en_ligne', 'En ligne'), ('en_presentiel', 'En présentiel')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(default='', max_length=100)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bourse.bourse')),
            ],
        ),
    ]
