# Generated by Django 4.2.7 on 2023-11-28 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bourse',
            name='likes',
            field=models.ManyToManyField(related_name='bourse_loved', to=settings.AUTH_USER_MODEL),
        ),
    ]
