# Generated by Django 4.2.7 on 2023-12-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('organisateur', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('email_reponses', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200)),
                ('caractere_reponse', models.CharField(choices=[('RC', 'Réponse courte'), ('P', 'Paragraphe'), ('CC', 'Case à cocher'), ('MC', 'Multiple Choix'), ('LD', 'Liste déroulante'), ('IF', 'Importer un fichier'), ('GCM', 'Grille à Choix multiples'), ('GCC', 'Grille à cases à cocher'), ('D', 'Date'), ('H', 'Heure')], max_length=3)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sondage.sondage')),
            ],
        ),
        migrations.CreateModel(
            name='OptionReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_option', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sondage.question')),
            ],
        ),
    ]
