# Generated by Django 4.2.7 on 2023-12-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sondage', '0002_remove_question_sondage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondage',
            name='email_reponses',
        ),
        migrations.RemoveField(
            model_name='sondage',
            name='question',
        ),
        migrations.RemoveField(
            model_name='sondage',
            name='type_reponse',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reponse', models.CharField(choices=[('RC', 'Réponse courte'), ('P', 'Paragraphe')], max_length=2)),
                ('question_texte', models.TextField()),
                ('reponse_texte', models.TextField(blank=True, null=True)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sondage.sondage')),
            ],
        ),
    ]
