# Generated by Django 4.2.7 on 2023-12-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sondage', '0003_remove_sondage_email_reponses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondage',
            name='organisateur',
        ),
        migrations.RemoveField(
            model_name='sondage',
            name='titre',
        ),
        migrations.AddField(
            model_name='sondage',
            name='todo_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
