# Generated by Django 4.2.7 on 2023-12-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sondage', '0005_choice_question_delete_sondage_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondagechoix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(max_length=30)),
                ('option_two', models.CharField(max_length=30)),
                ('option_three', models.CharField(max_length=30)),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
