# Generated by Django 4.2.7 on 2023-12-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calendar',
            table='tbcalendar',
        ),
    ]
