# Generated by Django 4.2.7 on 2023-12-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_alter_calendar_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='Events',
        ),
    ]
