# Generated by Django 4.2.7 on 2023-12-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_rename_calendar_events'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='tblevents',
        ),
    ]
