# Generated by Django 4.2.7 on 2023-12-26 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_revu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(default='', max_length=100)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=400)),
                ('authors', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=400)),
                ('methodology', models.CharField(max_length=400)),
                ('result', models.CharField(max_length=400)),
                ('Conclusion', models.CharField(max_length=400)),
                ('bibliography', models.CharField(max_length=400)),
                ('thanks', models.CharField(max_length=400)),
                ('conflict', models.CharField(max_length=400)),
                ('declarations', models.CharField(max_length=400)),
                ('file', models.FileField(default='', upload_to='revue_files/')),
                ('like_count_revu', models.BigIntegerField(default='0')),
                ('likes_revue', models.ManyToManyField(blank='True', default='None', related_name='like_revu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='comment_revu',
            name='revu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='science.revue'),
        ),
    ]
