# Generated by Django 4.2.7 on 2023-12-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0002_comment_revu_revue_delete_answer_delete_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revue',
            name='Conclusion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revue',
            name='authors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revue',
            name='bibliography',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revue',
            name='conflict',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revue',
            name='declarations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revue',
            name='introduction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revue',
            name='methodology',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revue',
            name='result',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revue',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revue',
            name='thanks',
            field=models.TextField(),
        ),
    ]
