# Generated by Django 4.2.7 on 2023-12-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0003_alter_revue_conclusion_alter_revue_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revue',
            name='authors',
            field=models.CharField(default='', max_length=500),
        ),
    ]
