# Generated by Django 4.2.7 on 2023-12-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0004_alter_revue_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_revu',
            old_name='revu',
            new_name='revue',
        ),
    ]
