# Generated by Django 4.2.7 on 2023-12-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0005_rename_revu_comment_revu_revue'),
    ]

    operations = [
        migrations.AddField(
            model_name='revue',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
